# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66b5bd0c2fc74d040bfdd603f0c1d794960a0372fea6da6099d00e6c7588105a0fffdb96e162bfba4d9a42c368c5c5db4c9bad453e3c35a00494732d8b2f02b1

test:
  secret_key_base: c78609b59d142dc02402fc5add2f3cbd8ca98f06d6c1445954d2333129694bdc41041868c3d74de1259541a8d7ae36e4cb1ab8893f2c8d2d32af1416ff028474

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
